### ISSUE TITLE
Add functions from reference and fix tests

### ISSUE THREAD

**Issue by M1ha-Shvn** [M1ha-Shvn/django-pg-hll#8]
As provided in [PR #7](https://github.com/M1ha-Shvn/django-pg-hll/pull/7) by @markallanson, not all hll functions available are implemented in this library.
I've found a [reference](https://pgxn.org/dist/hll/REFERENCE.html).

**TODO list**
- [x] ~Implement hll_set_defaults, hll_print~
- [x] Implement hll_schema_version, hll_type, hll_regwidth, hll_log2m, hll_expthresh, hll_sparseon functions
- [x] Implement hll_empty, ~hll_add_agg~ optional configuration arguments
- [x] ~Implement hll_eq, hll_ne filters and functions~
- [x] Rewrite test `HllFieldTest.test_create_custom_params` using hll empty optional parameters

**Comment by M1ha-Shvn** [comment]
I've digged a little bit inside django functions implementation and found out, that any additional function arguments can be passed to function "out of the box", so `HllEmpty(13, 2, 1, 0)` can be used without significant code changes. Refactored `HllFieldTest.test_create_custom_params`. Also added tests on `HllEmpty` with arguments.

**Comment by M1ha-Shvn** [comment]
I've desided not to implement `hll_set_defaults`, `hll_print` functions:
1. `hll_set_defaults` is much more migration-like ability, than aggregate/transform function
2. `hll_print` is a debug printing function, I don't see any django usage for it as well

**Comment by markallanson** [comment]
hll_set_defaults needs to be called on every connection and it applies to the connection only - it’s not a persistent setting.

**Comment by M1ha-Shvn** [comment]
> hll_set_defaults needs to be called on every connection and it applies to the connection only - it’s not a persistent setting.

If so, I see even less real need to use it inside django with its style and syntax

**Comment by M1ha-Shvn** [comment]
`hll_eq` and `hll_ne` functions doesn't require implementation, as standard django behavior with filter and exclude works well. Added some tests on filter/exclude with HllValues and editted documentation.

**Comment by M1ha-Shvn** [comment]
`hll_add_agg` function is not used directly in this library, as hll fields are joined over `||` operator. I will not implement it for now because:
1. I'm not sure of it's real use case. Suppose, it can be implemented with combination of `HllEmpty(1,2,3) | HllInteger(1)`
2. Adding this function will require big inner changes in library. Is it really necessary?

**Comment by M1ha-Shvn** [comment]
NOTE I've desided to release a major version, as this patch also makes breaking (not really sure about it) changes:
1. All cardinality fetches now return `FloatField` instead of `IntegerField`, as original cardinality functions do
2. `HllField` transformes are moved to separate location (`django_pg_hll.transport` instead of `django_pg_hll.fields`)
3. `HllField` parameters changed behavior: instead of hardcoding default values, it now bypasses defaults generation to database layer

**Comment by M1ha-Shvn** [comment]
Released [v2.0.0](https://github.com/M1ha-Shvn/django-pg-hll/releases/tag/v2.0.0)
